language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - rustup component add clippy
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo build --release --features --features "parq" ;
        cargo test --features "parq" ;
        cargo clippy -p tsxlib --features "parq" ;
    fi
  - cargo build --release
  - cargo build --release --features "json"
  - cargo test
  - cargo clippy -p tsxlib --features "json"

env:
  global:
    - RUST_BACKTRACE=1
